### ISSUE TITLE
sdcadm update cannot cope with multiple instances of mahi

### ISSUE THREAD

**Issue by sperreault** [joyent/sdcadm#10]
While trying to update sdc from 20150219 to 20150319 I got the following message:

[root@headnode (dc1) /var/tmp]# sdcadm update mahi
Finding candidate update images for the "mahi" service.
sdcadm update: error (Update): do not support the following changes:
{"type":"update-service","service":"mahi","image":"d51ee30a-ce82-11e4-8e36-dbd1841a085b"} 

It was deemed after looking at this gist https://gist.github.com/sperreault/82a1a4f29e9d302a7933 that it was because of the fact that sdcadm update cannot cope with multiple instances of mahi.

**Comment by kusor** [comment]
@sperreault upgrading multiple mahi instances is not yet supported, as you've figured out the hard way. It's on the short term plans anyway so, I'd say it should be implemented pretty soon.
