### ISSUE TITLE
sdcadm update mahi error message

### ISSUE THREAD

**Issue by sperreault** [joyent/sdcadm#11]
The error message when you try to update multiple instance of mahi doesn't lead to know that it's because of the fact that it cannot cope with multiple instances:

[root@headnode (dc1) /var/tmp]# sdcadm update mahi
Finding candidate update images for the "mahi" service.
sdcadm update: error (Update): do not support the following changes:
{"type":"update-service","service":"mahi","image":"d51ee30a-ce82-11e4-8e36-dbd1841a085b"} 

 See issue #10 for a more complete log of the issue.

**Comment by lloydde** [comment]
@sperreault with TOOLS-926 "sdcadm update: add support for multiple mahi instances update" now complete. I think this issue can be closed. Do you agree?

**Comment by sperreault** [comment]
Yes I agree

On Thursday, April 16, 2015, Lloyd Dewolf <notifications@github.com> wrote:

> @sperreault <https://github.com/sperreault> with TOOLS-926 "sdcadm
> update: add support for multiple mahi instances update" now complete. I
> think this issue can be closed. Do you agree?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joyent/sdcadm/issues/11#issuecomment-93838315>.
>


-- 
Sebastien Perrreault
Partner
Les Technologies Alesium Inc
P: 514-298-7193
F: 514-221-3668
E: sperreault@alesium.net

"Life's missed opportunities, at the end, may seem more poignant to us than
those we embraced--because in our imagination they have a perfection that
reality can never rival." -- Roger Ebert
