### ISSUE TITLE
sdcadm dc-maint start/stop errors if cloudapi is not on the headnode (or destroyed)

### ISSUE THREAD

**Issue by pannon** [joyent/sdcadm#12]
Have two `cloudpapi` instances one running on the headnode and the other running on a compute node. When `sdcadm dc-maint start/stop` is issued it produces the error below as it tries to execute `svcadm -z ....` for the remote `cloudapi` which (obviously) fails.

```
sdcadm dc-maint start
Getting SDC's sapi instances from SAPI
Putting cloudapi in read-only mode
Putting docker in read-only mode
Saving data center maintenance eta/message
sdcadm dc-maint: error: error running "/usr/sbin/svcadm -z 3b43e3ee-49da-4e79-9826-f2d7f610053b refresh config-agent" on server "..........": svcadm: invalid zone '3b43e3ee-49da-4e79-9826-f2d7f610053b'
```

Also the same error happens when the second `cloudapi` is destroyed - `sdcadm` still tries to execute `svcadm` in the destroyed zone.

This is kind of a cosmetic problem as the DC will go in and out of maintenance mode without issues anyway..

**Comment by kusor** [comment]
Yeah, right now having CloudAPI running on the HN - and most of the core components - is a requirement for `sdcadm` to work properly. I'll take a look at this and try to modify in the short term, since the fix is not that complex once we have sorted out updates of HA services running into different nodes.

**Comment by kusor** [comment]
Having CloudAPI not on the headnode is no longer a problem. Ditto for docker instance. And it's just using _"active"_ instances, so destroyed or missing instances shouldn't be a problem anymore
