### ISSUE TITLE
`sdcadm health -j -q` prints healthy services

### ISSUE THREAD

**Issue by bdha** [joyent/sdcadm#19]
Rather than only printing unhealthy services in JSON.

```
[root@headnode (us-east-1) ~]# sdcadm health -q
[root@headnode (us-east-1) ~]#
[root@headnode (us-east-1) ~]# sdcadm health -q -j | head
[
    {
        "type": "vm",
        "instance": "6cd3f2bb-79f7-480f-88fe-067936e8705f",
        "alias": "adminui0",
        "service": "adminui",
        "hostname": "headnode",
        "healthy": true
    },
    {
...
```

**Comment by kusor** [comment]
@bdha thanks for catching it. Looks like both options were understood as mutually exclusive, but that wasn't documented into the help/man page. There's no reason for that incompatibility between options, so it should be fixed now.
