### ISSUE TITLE
Documentation: Inconsistency on placement of moray nodes for HA

### ISSUE THREAD

**Issue by sodre** [joyent/sdcadm#23]
What is the recommended setup in HA for moray? Should one colocate it with the manatee host or away from it? 
The current documentation from joyent has two conflicting views.
- In [sdcadm/README.md](https://github.com/joyent/sdcadm#create-the-desired-number-of-moray-instances-for-ha) it reads (emphasis is mine):
  
  > A recommended setup includes two additional moray instances created **on the same CNs we added the manatees** on the previous ...
- While in the [Triton Documentation](https://docs.joyent.com/private-cloud/resilience#moray) it reads (emphasis is mine):
  
  > To deploy multiple moray instances, first determine which compute nodes that you will be using for the deployment. **Ideally, these nodes will not already contain manatee or zookeeper instances**.

**Comment by kusor** [comment]
@sodre if you have CNs to create the moray instances separated from the manatees, that would be great. Either way we have setups with both, manatee and moray instances on the same CN working perfectly fine so, no big deal on this

**Comment by sodre** [comment]
@kusor thanks for the response, I will continue to run them together with the manatee hosts.
