### ISSUE TITLE
--force-data-path option is not applicable for `sdcadm create portolan`

### ISSUE THREAD

**Issue by gochist** [joyent/sdcadm#28]
Regarding https://github.com/joyent/triton/issues/214, I tried to create additional portolan instance but it failed with a message as below.

```
[root@headnode (june-hp650-2) ~]# sdcadm create portolan -s d4db99d7-e164-c947-9564-ff8c1d42954d --skip-ha-check 
sdcadm create: error: portolan updates are locked: {"type":"create","service":"portolan"} (use --force-data-path flag)
```

There's no way to create multiple portolan instances with `sdcadm create` because it doesn't allow `--force-data-path` option currently.

**Comment by gochist** [comment]
I have made a PR at https://cr.joyent.us/#/c/935.

**Comment by trentm** [comment]
A side note for this issue: There are a couple reasons to beware having multiple portolan instances:

1. While the engineers involved say that portolan should function properly with multiple instances, that hasn't been well tested yet.
2. `sdcadm` doesn't have support for deleting added instances. One would have to manually delete extra instances of portolan via something like `sdc-sapi /instances/$uuid -X DELETE`.
3. Once there are multiple portolan instances, current `sdcadm` won't be able to update them. Attempts to update the whole service will fail as follows:

```
[root@headnode (coal) ~]# sdcadm up portolan --force-data-path
Using channel dev
sdcadm up: error: do not support the following changes:
    {"type":"update-service","service":"portolan","image":"09bed990-6b20-11e6-86c5-3b05d15c6966"}
```

One *would* be able to update 'portolan0' on the headnode via `sdcadm up portolan0 --force-data-path`, but other instances on servers other than the headnode won't be updatable via sdcadm.
