### ISSUE TITLE
Update to 20170316 fails to upgrade moray,cloudapi..

### ISSUE THREAD

**Issue by ofsole** [joyent/sdcadm#31]
When I run sdcadm up moray -y, got the following messages.
------------------------------------------------------------------------------
[root@headnode (office) ~]# sdcadm up moray -y

Finding candidate update images for the "moray" service.
Using channel release

This update will make the following changes:
    download 1 image (53 MiB):
        image 319e6fec-09b9-11e7-bc13-d76594d2f0c3
            (manta-moray@release-20170316-20170315T194752Z-gd23510d)
    update "moray" service to image 319e6fec-09b9-11e7-bc13-d76594d2f0c3
        (manta-moray@release-20170316-20170315T194752Z-gd23510d):
        instance "bada7ea7-966c-4268-803c-ffe28c99f60f" (moray0) on server 44454c4c-5700-1030-8052-b2c04f4e3632

Create work dir: /var/sdcadm/updates/20170325T020806Z
Downloading image 319e6fec-09b9-11e7-bc13-d76594d2f0c3
    (manta-moray@release-20170316-20170315T194752Z-gd23510d)
Imported image 319e6fec-09b9-11e7-bc13-d76594d2f0c3
    (manta-moray@release-20170316-20170315T194752Z-gd23510d)
"moray" VM already has a delegate dataset
Updating image for SAPI service "moray"
    service uuid: 5148c896-785b-4fd6-aee2-b56508daf7b1
Installing image 319e6fec-09b9-11e7-bc13-d76594d2f0c3
    (manta-moray@release-20170316-20170315T194752Z-gd23510d)
Update error: EXCEPTION: InternalError: InternalError: error importing VM image 319e6fec-09b9-11e7-bc13-d76594d2f0c3:
        argv: ["/opt/smartdc/bin/sdc-oneachnode","-n 44454c4c-5700-1030-8052-b2c04f4e3632 ","/usr/sbin/imgadm import -q 319e6fec-09b9-11e7-bc13-d76594d2f0c3"]
        exit status: 20
        stdout:
HOSTNAME              STATUS
headnode              <ERROR: timeout for host 44454c4c-5700-1030-8052-b2c04f4e3632>
        stderr:
ERROR: execution failed on some nodes

  execution failed on nodes:
    headnode; caused by Error: Command failed: ERROR: execution failed on some nodes

  execution failed on nodes:
    headnode

    at /opt/smartdc/sdcadm/lib/procedures/shared.js:737:29
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
Caused by: EXCEPTION: Error: Error: Command failed: ERROR: execution failed on some nodes

  execution failed on nodes:
    headnode

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
sdcadm up: error (InternalError): error importing VM image 319e6fec-09b9-11e7-bc13-d76594d2f0c3:
        argv: ["/opt/smartdc/bin/sdc-oneachnode","-n 44454c4c-5700-1030-8052-b2c04f4e3632 ","/usr/sbin/imgadm import -q 319e6fec-09b9-11e7-bc13-d76594d2f0c3"]
        exit status: 20
        stdout:
HOSTNAME              STATUS
headnode              <ERROR: timeout for host 44454c4c-5700-1030-8052-b2c04f4e3632>
        stderr:
ERROR: execution failed on some nodes

  execution failed on nodes:
    headnode

and saw the process zfs receive running in the background didn't exit, wait for long time the same issue, reboot, then run the same command(sdcadm up moray -y), the same issue occur :(
--------------------------------------------------------------------------------------------------------
[root@headnode (office) ~]# ps -ef | grep 319e6fec-09b9-11e7-bc13-d76594d2f0c3
    root 18098 18088   0 02:12:42 ?           0:00 /usr/sbin/zfs receive zones/319e6fec-09b9-11e7-bc13-d76594d2f0c3-partial
    root 18157 17780   0 02:14:09 pts/2       0:00 grep 319e6fec-09b9-11e7-bc13-d76594d2f0c3
[root@headnode (office) ~]# zpool history | grep 319e6fec-09b9-11e7-bc13-d76594d2f0c3
[root@headnode (office) ~]# zfs list -t all | grep 319e6fec-09b9-11e7-bc13-d76594d2f0c3
zones/319e6fec-09b9-11e7-bc13-d76594d2f0c3-partial                      184M  1.02T   370M  /zones/319e6fec-09b9-11e7-bc13-d76594d2f0c3-partial
[root@headnode (office) ~]# 

Attachmeng is the sdcadm log, any help appreciated. 

[sdcadm_headnode_2017-03-25T020000.txt](https://github.com/joyent/sdcadm/files/869597/sdcadm_headnode_2017-03-25T020000.txt)

**Comment by kusor** [comment]
Hi @ofsole,

the sdcadm log isn't very helpful here, since it's just telling us that there has been a problem importing the image which, for your later comments, looks like it's due to some zfs issue.

Is this a COAL setup or bare metal SmartOS installation?

Have you tried to manually download and import the image before attempting moray update?

**Comment by ofsole** [comment]
Hi @kusor 
Sorry for the late reply due to my vacation, It's a bare metal Smartos installation.

I try to use sdc-imgadm import -f filename -m manifest, it works, and I use imgadm import "uuid", it stuck here, sdc-imgadm delete and reimport didn't work either.

Take one for example, 
_before I import adminui(734a045c-09b8-11e7-945a-5b62ba725083),_
[root@headnode (office) ~]# ps -ef | grep 734a045c-09b8-11e7-945a-5b62ba725083
    root 88209 88182   0 02:08:50 pts/2       0:00 grep 734a045c-09b8-11e7-945a-5b62ba725083

_then I execute the following command,_
[root@headnode (office) ~]# imgadm import 734a045c-09b8-11e7-945a-5b62ba725083
Importing 734a045c-09b8-11e7-945a-5b62ba725083 (adminui@release-20170316-20170315T193735Z-g7c701fd) from "http://imgapi.office.otms.lan"
Gather image 734a045c-09b8-11e7-945a-5b62ba725083 ancestry
Image fd2cc906-8938-11e3-beab-4359c665ac99 already installed
Must download and install 1 image (79.4 MiB)
Downloaded image 734a045c-09b8-11e7-945a-5b62ba725083 (79.4 MiB)
Download 1 image        [===================================>] 100%  79.47MB                  
...e7-945a-5b62ba725083 [===================================>] 100%  79.47MB  22.38MB/s     3s
---stop here---

_I can see zfs receive running in backgroung._
[root@headnode (office) ~]# ps -ef | grep 734a045c-09b8-11e7-945a-5b62ba725083
    root 88414 88227   0 02:12:03 pts/3       0:00 grep 734a045c-09b8-11e7-945a-5b62ba725083
    root 88274 88248   0 02:09:30 pts/2       0:01 **/usr/sbin/zfs receive zones/734a045c-09b8-11e7-945a-5b62ba725083-partial**

**Comment by kusor** [comment]
Hi @ofsole 

This is definitely unrelated to sdcadm itself and more like a zfs issue. What platform image are you running? Could you try a platform update and retry?

**Comment by ofsole** [comment]
Hi @kusor 
After updating the platform to the latest, it works like a charm, thanks for your great help.
