### ISSUE TITLE
`sdcadm` unresponsive after self-update to `release-20170608-20170608T210823Z-g1fef837`

### ISSUE THREAD

**Issue by themisanthrope** [joyent/sdcadm#32]
Hi there,

I have found that after doing new install (using the current Triton installer `release-20170608-20170608T213206Z-gb9ac8cc`) `sdcadm` is often either unresponsive or times out, with successful operations being a fraction of those tried.

If I install an older build of Triton (I tried `release-20170316-20170315T223833Z-gc64b017`), `sdcadm` works without issue _until_ I issued `sdcadm set channel release && sdcadm self-update --latest`. After doing this, I have the same non-responsive issues as before.

For the time being, I have manually downgraded `sdcadm`, so I have a working system, but this did prevent me doing a clean install for a new headnode using the latest USB image.

If you need more information, please let me know and I'll do my best to get it for you.

Adam

Examples of failures;
`sdcadm post-setup common-external-nics` appeared to hang this morning, but I tried it again this afternoon and it worked without issue.
`sdcadm post-setup cloudapi` ran immediately after `sdcadm post-setup common-external-nics` and completed pretty much immediately.
`sdcadm post-setup fabrics -c /var/tmp/fabric_cfg.json` ran a few minutes after `sdcadm post-setup cloudapi` and was hung for an hour before I gave it `^C`.

I have run the final command via `truss` and it just appears to sleep indefinitely: `waitid(P_ALL, 0, 0x08047930, WEXITED|WTRAPPED) (sleeping…)`

```
# sdcadm post-setup fabrics -c /var/tmp/fabric_cfg.json
Downloading image de411e86-548d-11e4-a4b7-3bb60478632a
    (sdc-base@14.2.0)
Imported image de411e86-548d-11e4-a4b7-3bb60478632a
    (sdc-base@14.2.0)
Downloading image 10c3725c-50a1-11e7-824b-2bdc7d34174f
    (portolan@master-20170614T011100Z-gcb0aad5)
Imported image 10c3725c-50a1-11e7-824b-2bdc7d34174f
    (portolan@master-20170614T011100Z-gcb0aad5)
Creating "portolan" service
Creating "portolan" instance
Finished portolan setup
Downloading image 6034ca2a-28b5-11e7-a5b7-8b9ff9db3f2a
    (nat@master-20170424T061259Z-ge997023)
Imported image 6034ca2a-28b5-11e7-a5b7-8b9ff9db3f2a
    (nat@master-20170424T061259Z-ge997023)
Creating "nat" service
Created nat service
Adding fabric configuration
Restarting config of services using "fabric_cfg": napi, vmapi, dhcpd
sdcadm post-setup fabrics: error: first of 1 error: spawn error:
argv: ["/opt/smartdc/bin/sdc-login","dhcpd","cd /opt/smartdc/config-agent && ./build/node/bin/node agent.js -s"]
exit code: 1
exit signal: null
stdout:

stderr:
sdcadm: error (SDCClient): sapi client error (RequestExpired): Date header Wed, 21 Jun 2017 13:49:01 GMT is too old
```

**Comment by kusor** [comment]
Hi Adam,

can you upload SAPI and sdcadm logs somewhere so we can take a look? If you
don't try to setup fabrics, is the issue gone? Can we take a look at the
fabrics config file you're using?

For the time being, I have manually downgraded sdcadm, so I have a working
> system, but this did prevent me doing a clean install for a new headnode
> using the latest USB image.
>

If this is a sdcadm issue, you can always downgrade it to a previous
version using the uuid from one of the images retrieved from updates-imgadm
list name=sdcadm -C release.

-- Pedro P. Candel

**Comment by themisanthrope** [comment]
> can you upload SAPI and sdcadm logs somewhere so we can take a look?
Will do - I'll grab the logs off the box tomorrow

> If you don't try to setup fabrics, is the issue gone?
No - this was even happening with `post-setup common-external-nics`, which is pretty much the first thing I ran after making sure the default zones were healthy. Setting up the fabrics came after that, but I had to retry both several times before they completed.

> Can we take a look at the fabrics config file you're using?
Sure, it's not a complex setup at all - I'm only using a single NAT pool. I'll grab that tomorrow.

> If this is a sdcadm issue
It _feels_ like it might be, but I could be wrong. I'll do another fresh install with the latest USB build on a different box and see if only downgrading `sdcadm` fixes the issue.

**Comment by themisanthrope** [comment]
Apologies for the delay! I did a fresh install with `release-20170608-20170608T213206Z-gb9ac8cc` on different hardware, same issue. I'm about to install the latest build from scratch (on the same box), and I'll report back.

However the information you requested is below.

**IPMI Console Input**
*Setting up LACP directly after setup*
```
==> Setup complete (in 1093 seconds). Press [enter] to get login prompt.





         *--+--*--*
         |\ |\ |\ |\      J O Y E N T
         | \| \| \| \     #####  ####   #  #####  ###   #   # TM
         +--*--+--*--*      #    #   #  #    #   #   #  ##  #
         |\ |\ |\ |\ |      #    ####   #    #   #   #  # # #
         | \| \| \| \|      #    #  #   #    #   #   #  #  ##
         *--+--+--+--+      #    #   #  #    #    ###   #   #
          \ |\ |\ |\ |
           \| \| \| \|     SmartOS
            *--+--*--*      build: 20170608T172457Z


headnode ttyb login: root
Password:
2017-07-01T11:12:13+00:00 headnode login: [ID 644210 auth.notice] ROOT LOGIN /dev/term/b
- SmartOS (build: 20170608T172457Z)
You have new mail.
# dladm show-phys -m
LINK         SLOT     ADDRESS            INUSE CLIENT
e1000g0      primary  68:5:ca:4d:0:62    yes  e100g0
e1000g2      primary  68:5:ca:4a:fe:6    yes  e1000g2
e1000g1      primary  68:5:ca:4d:0:63    yes  e1000g1
e1000g3      primary  68:5:ca:4a:fe:7    yes  e1000g3
# sdc-usbkey mount ; vi /mnt/usbkey/config
/mnt/usbkey
# sdc-usbkey unmount && reboot
2017-07-01T11:17:20+00:00 headnode reboot: [ID 330035 auth.crit] initiated by root on /dev/term/b
reboot: Halting 21 zones.
reboot: Completing system halt.
rebooting...
```
*Attempting configuration*
```
headnode ttyb login: root
Password:
Last login: Sat Jul  1 11:12:13 on term/b
2017-07-01T11:22:16+00:00 headnode login: [ID 644210 auth.notice] ROOT LOGIN /dev/term/b
- SmartOS (build: 20170608T172457Z)
You have new mail.
# ping 10.0.104.5
10.0.104.5 is alive
# ping 10.0.112.5
10.0.112.5 is alive
# curl http://purple.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://www.purple.com/">here</a>.</p>
</body></html>
# zpool set autoexpand=on zones
# zpool set autoreplace=on zones
# zfs set compress=lz4 zones
# zfs set compress=off zones/swap
# zfs set compress=off zones/usbkey
# sdc-healthcheck
# sdc-healthcheck
ZONE                                 STATE           AGENT               STATUS
global                               running         -                   online
assets                               running         -                   online
sapi                                 running         -                   online
binder                               running         -                   online
manatee                              running         -                   online
moray                                running         -                   online
amonredis                            running         -                   online
ufds                                 running         -                   online
workflow                             running         -                   online
amon                                 running         -                   online
sdc                                  running         -                   online
papi                                 running         -                   online
napi                                 running         -                   online
rabbitmq                             running         -                   online
imgapi                               running         -                   online
cnapi                                running         -                   online
dhcpd                                running         -                   online
fwapi                                running         -                   online
vmapi                                running         -                   online
ca                                   running         -                   online
mahi                                 running         -                   online
adminui                              running         -                   online
global                               running         ur                  online
global                               running         smartlogin          online
# sdcadm post-setup common-external-nics
sdcadm: error (SDCClient): sapi client error (RequestExpired): Date header Sat, 01 Jul 2017 11:25:48 GMT is too old
# sdcadm post-setup common-external-nics
Added external nic to adminui
Added external nic to imgapi
# sdc-vmadm ips -p $(sdc-vmname adminui)
10.0.112.6
# sdcadm post-setup cloudapi
cloudapi0 zone created
# sdc-vmadm ips -p $(sdc-vmname cloudapi)
10.0.112.8

**Log files requested**
https://transfer.sh/U8v8W/sapi.log
https://transfer.sh/14qqXF/sapi.2.log
https://transfer.sh/TU28A/sdcadm.log

**Generic fabric configuration**
https://transfer.sh/iBXLS/fabric_cfg.json

**Comment by themisanthrope** [comment]
Also getting the same issue on the latest release `20170623T043049Z-gb9ac8cc`.

**Comment by kusor** [comment]
@themisanthrope The sdcadm log isn't very useful, it's full of failed attempts to resolve `binder.development.infra.victoriaplum.com` on Binder. Same for the SAPI logs. sdcadm logs for individual commands can be found under `/var/log/sdcadm/logs/` right after you exec each command.

Could you give this a try using `sdcadm -v <CMD>`? That way it'll log everything to stderr/stdout too. Also, right before you start with the setup process, mind to run `sdcadm health` instead of `sdc-healthcheck`.

Regarding the first failure when trying to setup `common-external-nics`, is the NTP service of the GZ running w/o errors?

**Comment by themisanthrope** [comment]
@kusor The box I was originally using is now in production, so tonight In upgraded a previously working box and have run into the same problem.

The NTP service does appear to be running and is not reporting any errors. The date and time also follow the NTP server on our network faithfully.

Interestingly, after doing the `sdcadm` upgrade, all I'm getting to the console (in verbose mode) seems to be complaints about not being able to resolve the `binder` zone again (`CueBallDNSResolver`).

Full console log is available at http://termbin.com/bacp - I'm going to manually downgrade `sdcadm` on this box for now, but this one is not in production use at the moment, so any required tests can be made... Just let me know.

**Comment by themisanthrope** [comment]
FYI, I couldn't downgrade `sdcadm` using it's own self-update function either, due to the same problem.

I ended up just clearing out the contents of `/opt/smartdc/sdcadm/` and copying in the contents of `/var/sdcadm/self-updates/20170322T091211Z/sdcadm.old/`.

**Comment by kusor** [comment]
This issue should be already fixed into the most recent sdcadm versions.

Note that you can always bypass a broken sdcadm version by installing the latest available shar:

```
updates-imgadm get-file -o latest-sdcadm.sh $(updates-imgadm list name=sdcadm --latest -H -o uuid)
bash latest-sdcadm.sh
```
