### ISSUE TITLE
Disable fabric network

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/sdcadm#33]
Is the any procedure to rollback https://docs.joyent.com/private-cloud/install/advanced-configuration#setup-fabric-networks ?

Apparently after enabling fabric networks, it is not possible to provision docker instances outside of the fabric network.

After removing all the fabric networks created, is it possible to "disable" it and get back to the point where we were before running
`sdcadm post-setup fabrics` and `sdcadm post-setup underlay-nics` ?

**Comment by kusor** [comment]
No, there isn't such possibility, at least automated. It might require manual modifications and re-configuration of the whole Triton setup in order to make it possible.
