### ISSUE TITLE
sdcadm experimental update-gz-tools & update-agents

### ISSUE THREAD

**Issue by pannon** [joyent/sdcadm#8]
I am raising this here as others might experience this after upgrading gz-tools and agents in SDC with:

```
sdcadm experimental update-gz-tools --latest
sdcadm experimental update-agents --latest
```

After finishing the whole SDC update process, running `sdc-healthcheck` highlighted an issue with `global` services.
`svcs -xv` reported `svc:/smartdc/application/config-agent:default` in maintenance mode.

Closer examination of `/var/svc/log/smartdc-application-config-agent:default.log` revealed that `sdc-config-agent` could not find `/opt/smartdc/agents/lib/node_modules/config-agent/etc/config.json` file as the whole `etc` directory was missing.

Soution was to recreate `/opt/smartdc/agents/lib/node_modules/config-agent/etc` and `config.json` manually.

Unsure why this might have happened, at this stage.

**Comment by lloydde** [comment]
@pannon is this a CoaL environment? Did you enable dev-headnode-prov?

**Comment by pannon** [comment]
Hi @lloydde, not a CoaL environment, this is in our lab/training setup 1 headnode and 2 compute nodes. We have a prod environment as well, have not tried it there yet.

Did not enable dev-headnode-prov.

**Comment by lloydde** [comment]
@pannon thank you for eliminated that it is specific to CoaL with 'dev-headnode-prov' which is the env that I've reproduced the symptom in so far.

**Comment by kusor** [comment]
@pannon which version of `sdcadm` are you using?. I've just tried and I'm completely unable to reproduce with latest `sdcadm`:

```bash
[root@headnode (coal) ~]# sdcadm experimental update-agents --latest
Downloading agentsshar image 2e1218f6-517b-48ba-812f-74699fa16dab (1.0.0-master-20150224T064558Z-gd3c2031) to /var/tmp/agents-2e1218f6-517b-48ba-812f-74699fa16dab.sh
Executing agents installer across data center
Done.

[root@headnode (coal) ~]# sdcadm --version
sdcadm 1.5.1 (master-20150224T125329Z-gf0a68b3)
```

Do you have the log file for the upgrade?. I somewhat remember this happening with an older agents version, mind to update `sdcadm` and try again, in order to confirm that you can reproduce?.

Thanks in advance.

**Comment by pannon** [comment]
Version is:
```
sdcadm 1.5.1 (master-20150220T182922Z-g2503870)
```
Logs in `/var/log/sdcadm/` ?

**Comment by trentm** [comment]
Possibly related is the recently fixed https://smartos.org/bugview/AGENT-853

However, more of a guess is that you were upgrading from a significantly older COAL? Not sure of that tho.  @pannon: Yes logs on /var/log/sdcadm/ might pinpoint the issue.  Also the /var/tmp/agent_install.log would really help.

**Comment by pannon** [comment]
@trentm not using CoaL, this happened on our Lab setup - all physical nodes. I will dig out the logs..

**Comment by pannon** [comment]
Uploaded relevant [logs](https://us-east.manta.joyent.com/ptoth@oss.co.nz/public/sdcadm-debug-25022015.tar.gz) (hopefully sanitized correctly).

**Comment by trentm** [comment]
@pannon Thanks! I'll have a look, but I'm not sure if this will reveal anything. I think we're finding that we need to revisit the install/setup of a few of the recent agents (config-agent, vm-agent, net-agent, cn-agent). I'll keep this ticket open until we have another run at that.

**Comment by lloydde** [comment]
@pannon could you try updating again if you haven't already done so? This symptom should now be resolved.

**Comment by pannon** [comment]
Thanks @lloydde , have already upgraded and have not seen this issue. Thanks everyone involved!
